# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F6aQi4SeZI-EuRsFNY502oTuahlhk6LR
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

BaseDados = pd.read_csv('Dados_queimadas.csv', encoding='latin-1')

#print(BaseDados.isnull().sum())
#print(BaseDados.head())
#print(BaseDados.describe())
#print(BaseDados.nunique())

queimadas = BaseDados.groupby(by=['year']).sum().reset_index()

plt.figure(figsize=(14,5))
plt.title("Gráfico de queimadas no Brasil")
sns.lineplot(data=queimadas, x='year', y='number', estimator='sum', color="Red")
sns.set_theme(style="darkgrid")
plt.grid(True)
plt.xlabel("Quantidade de queimadas")
plt.ylabel("Período")

plt.show()