# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EAVCs1pSomWUykznmqcmxzC6hVypDXIl
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

BaseDados = pd.read_csv('Dados_queimadas.csv', encoding='latin-1')

queimadas = BaseDados.groupby(by=['state']).sum().reset_index()[['state','number']].sort_values("number",ascending=False)

print(queimadas.head())

plt.figure(figsize=(15,5))

plt.title('Queimadas por Estados')

plt.bar(queimadas.state, queimadas.number)
plt.ylabel("Quantidade")
plt.xlabel("Estados")
plt.xticks(rotation=90)

plt.show()