# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mRNfr8Bjk7UHF2gld7fK2Lbig3GbYEMu
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

BaseDados = pd.read_csv('Dados_queimadas.csv', encoding='latin-1')

queimadas = BaseDados.groupby(by=['state']).sum().reset_index()[['state','number']].sort_values("number",ascending=False)
lista = queimadas['state'][0:10].values
plt.figure(figsize=(13,5))
for Coluna in lista:
  filtro = BaseDados.loc[BaseDados['state'] == Coluna]
  analise = filtro.groupby(by=['year']).sum().reset_index()

 #Queimadas por ano dos 10 estados com mais queimadas
  plt.title('Queimadas por ano')
  sns.lineplot(data=analise, x='year', y='number')


plt.grid(True)
plt.xlabel('Período')
plt.ylabel('Número de queimadas')
plt.legend(lista, bbox_to_anchor=(1,0.8))
sns.set_theme(style="darkgrid")
plt.show()